source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

gem 'fastlane'
gem 'cocoapods', '~> 1.13'
# 修复 ActiveSupport 版本兼容性问题
gem 'activesupport', '~> 6.1.7', '< 7.0'